export const defaultHeaderValues: Record<string, string> = {
  Accept: 'application/json',
  'Accept-Encoding': 'gzip, deflate, br',
  'Accept-Language': 'en-US,en;q=0.9',
  Authorization: 'Bearer ',
  'Cache-Control': 'no-cache',
  'Content-Type': 'application/json',
  'User-Agent': 'MyApp/1.0',
  Host: '',
  Referer: '',
  Cookie: 'sessionId=',
  Origin: '',
  'If-None-Match': '',
  'If-Modified-Since': '',
  Connection: 'keep-alive',
  'Upgrade-Insecure-Requests': '1',
};
